---
# Variables for splunkbaseinstall
splunk_binary: splunk-7.1.2-a0c72a66db66-Linux-x86_64.tgz
splunk_binary_url: "https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.1.2&product=splunk&filename=splunk-7.1.2-a0c72a66db66-Linux-x86_64.tgz&wget=true"
install_dir: '/opt'
splunk_path: '/opt/splunk'
splunk_check_path: '/opt/splunk/bin'
splunk_owner: splunkp
splunk_group: splunkp
